import PDFDocument from 'pdfkit';

export const generateAdherencePDF = (data, stream) => {
    const doc = new PDFDocument({ margin: 50 });

    // Stream the PDF to the response
    doc.pipe(stream);

    // --- Header ---
    doc.fontSize(25).text('ADHERIX: Clinical Adherence Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'right' });
    doc.moveDown();
    doc.hr = () => doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.hr();
    doc.moveDown();

    // --- Patient Info ---
    doc.fontSize(16).text('Patient Information', { underline: true });
    doc.fontSize(12).text(`Name: ${data.user.name}`);
    doc.text(`Email: ${data.user.email}`);
    doc.text(`Reliability Index: ${data.reliability}%`);
    doc.moveDown();

    // --- Summary Table ---
    doc.fontSize(16).text('Adherence Summary (Last 7 Days)', { underline: true });
    doc.moveDown();

    data.logs.forEach((log, index) => {
        doc.fontSize(10).text(
            `${index + 1}. ${log.medName} | Scheduled: ${log.scheduledTime} | Status: ${log.status.toUpperCase()}`,
            { bullet: true }
        );
    });

    if (data.logs.length === 0) {
        doc.text('No logs recorded for this period.');
    }

    // --- Footer ---
    doc.moveDown(2);
    doc.fontSize(10).text('This is an automated clinical report generated by the Adherix Engine.', {
        align: 'center',
        color: 'grey'
    });

    doc.end();
};